import "@/assets/global.css"
import Layout from '@/components/Layout'
import favicon from '@/assets/favicon.ico'
import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Simeon Davenport | Computer Programmer Portfolio',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={favicon.src} sizes="any" />
      </head>
      <Layout children={children} />
    </html>
  )
}