import "@/assets/global.css"
import Layout from '@/components/Layout'
import favicon from '@/assets/favicon.ico'

export const metadata = {
  title: 'Simeon Davenport | Computer Programmer Portfolio',
  description: 'Generated by Next.js',
  name: "width=device-width, initial-scale=1.0"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={favicon.src} sizes="any" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </head>
      <Layout children={children} />
    </html>
  )
}